server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  name: metrics-topic
